package codegen

import (
	"html/template"
	"io"

	"github.com/koud-fi/pkg/schema"
)

var goTypeTemplate = template.Must(template.New("go-type").
	Funcs(map[string]any{
		"tags": func(t schema.Type, key string) string {
			return "TODO"
		},
	}).
	Parse(`
package codegen

// This code is generated by go generate.
// DO NOT EDIT BY HAND!

type TestType struct {
{{- range $k, $v := .Properties}}
	{{$k}} {{$v.Type -}}
{{ end }}
}
	`))

func GoType(w io.Writer, t schema.Type) error {
	return goTypeTemplate.Execute(w, t)
}
